from abc import ABC, abstractmethod
from typing import Dict, Any, List, Optional
import json

class LLMProvider(ABC):
    @abstractmethod
    def generate(self, system_prompt: str, user_prompt: str, context: Optional[str] = None) -> str:
        pass

class LocalStubProvider(LLMProvider):
    """
    A stub provider that returns templates based on the context provided.
    This simulates the LLM's role of converting data to text.
    """
    def generate(self, system_prompt: str, user_prompt: str, context: Optional[str] = None) -> str:
        # In a real scenario, this would call a model.
        # Here we look at the query and context to form a response.
        
        if not context:
            return "I couldn't find any relevant data to answer your question."
            
        # Context is expected to be a stringified JSON or summary.
        # We'll just wrap it nicely.
        
        return f"Based on the data:\n\n{context}\n\n(Generated by LocalStubProvider)"

# Optional: Real local provider if we had one
class OllamaProvider(LLMProvider):
    def __init__(self, model="llama3:instruct"):
        self.model = model
        self.api_url = "http://localhost:11434/api/generate"
        
    def generate(self, system_prompt: str, user_prompt: str, context: Optional[str] = None) -> str:
        import requests
        try:
            full_prompt = f"{system_prompt}\n\nContext:\n{context}\n\nUser: {user_prompt}\nAssistant:"
            payload = {
                "model": self.model,
                "prompt": full_prompt,
                "stream": False
            }
            res = requests.post(self.api_url, json=payload)
            if res.ok:
                return res.json().get("response", "Error parsing Ollama response")
            return f"Ollama Error: {res.status_code}"
        except Exception as e:
            return f"Ollama Connection Error: {e}"

class QwenProvider(LLMProvider):
    def __init__(self, model_name="Qwen/Qwen2.5-1.5B-Instruct"):
        from transformers import AutoModelForCausalLM, AutoTokenizer
        import torch
        
        print(f"Loading model {model_name}...")
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModelForCausalLM.from_pretrained(
            model_name,
            torch_dtype=torch.float32, # CPU friendly
            device_map="cpu"
        )
        print("Model loaded.")

    def generate(self, system_prompt: str, user_prompt: str, context: Optional[str] = None) -> str:
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Context:\n{context}\n\nQuestion: {user_prompt}"}
        ]
        
        text = self.tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )
        
        model_inputs = self.tokenizer([text], return_tensors="pt").to(self.model.device)
        
        generated_ids = self.model.generate(
            **model_inputs,
            max_new_tokens=512
        )
        
        generated_ids = [
            output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
        ]
        
        response = self.tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
        return response
